POST http://localhost:3000/api/openai/lang?lang=python
###
POST http://localhost:3000/api/openai/lang?lang=ruby
###
POST http://localhost:3000/api/openai/lang?lang=perl
###
POST http://localhost:3000/api/openai/lang?lang=php
###
POST http://localhost:3000/api/openai/lang?lang=java
###
POST http://localhost:3000/api/openai/lang?lang=go
###
POST http://localhost:3000/api/openai/lang?lang=rust
###
POST http://localhost:3000/api/openai/lang?lang=javascript
###
POST http://localhost:3000/api/openai/lang?lang=typescript
###
POST http://localhost:3000/api/openai/lang?lang=c
