version: '3'

volumes:
  node_modules_volume:

services:
  app:
    build:
      context: .
    volumes:
      - ..:/app
      - node_modules_volume:/app/node_modules
    ports:
      - "3000:3000"
    command: sleep infinity

  neo4j:
    image: "neo4j:latest"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/logs:/logs
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_connector_https_advertised__address=localhost:7473
      - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms.connector.bolt.tls_level=OPTIONAL
